obj-$(CONFIG_DRAM_SUN50I_H6)	+= init_DRAM.o \
			readwritel.o \
			eye_delay_compensation.o \
			ccm_set_pll_ddr_sscg.o \
			ccm_set_pll_ddr_clk.o \
			dqs_gate_detect.o \
			auto_scan_dram_config.o \
			auto_scan_dram_size.o \
			auto_scan_dram_type.o \
			auto_scan_dram_rank_width.o \
			auto_set_timing_para.o \
			mctl_core_init.o \
			mctl_sys_init.o \
			mctl_com_init.o \
			mctl_channel_init.o \
			dramc_simple_wr_test.o \
			set_master_priority.o \
			set_master_priority_pad.o


