# $Id$
#
# Makefile
#
# Copyright (C) 2021 Chales Yu
#
# For now , Some vendor still sell this product with
# cheap price. But it has a new USB id 0fe6:9702, speed
# test show it only can reach to 10Mbps.
#

obj-m		:=
obj-m		+= sr9700.o


ifeq ($(MAKING_MODULES),1)

-include $(TOPDIR)/Rules.make
endif
